stages:
  preprocess:
    cmd: \ -p preprocess.input,preprocess.output \ -d src/preprocess.py -d 
      data/raw/data.csv \ -o data/processed/data.csv \ python src/preprocess.py
  train:
    cmd: \ -p train.data, train.model, 
      train.random_state,train.n_estimators,train.max_depth \ 
      -d src/train.py -d data/process/data.csv \
      -o models/model.pkl \ 
      python src/train.py

  evaluate:
    cmd: \ -d src/evaluate.py -d models/model.pkl -d data/preprocessed/data.csv 
      \ python src/evaluate.py
